/**
 * Pre-computed emoji embeddings
 * Generated by: scripts/generateEmojiEmbeddings.ts
 * Model: Xenova/all-MiniLM-L6-v2
 * Count: 1914 emojis
 * Generated: 2025-12-22T01:23:54.472Z
 */

export interface PrecomputedEmbeddings {
  version: number;
  modelId: string;
  embeddingDim: number;
  count: number;
  emojis: string[];
  embeddingsBase64: string;
}

// Import the JSON data
import embeddingsData from './emojiEmbeddings.json';

export const precomputedEmbeddings: PrecomputedEmbeddings = embeddingsData as PrecomputedEmbeddings;

/**
 * Decode the base64 embeddings into a Float32Array
 */
export function decodeEmbeddings(data: PrecomputedEmbeddings): Map<string, number[]> {
  const binary = atob(data.embeddingsBase64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  const floats = new Float32Array(bytes.buffer);

  const embeddings = new Map<string, number[]>();
  for (let i = 0; i < data.count; i++) {
    const start = i * data.embeddingDim;
    const end = start + data.embeddingDim;
    const emoji = data.emojis[i];
    if (emoji) {
      embeddings.set(emoji, Array.from(floats.slice(start, end)));
    }
  }

  return embeddings;
}
